Examples of largest number, century and Palindrome
Regis25/Dev-Fundamentals-I pull request #1
Opened 2019-10-23 19:54 UTC by Regis25

2019-10-24 14:10 UTC, uabarahona requested changes

2019-10-24 14:10 UTC, barahonajm commented on Assigment 1/Example1.java
> +    public static double largestNumber(final double digits) {
Awesome, but this will need to return an integer as we only need the number avoiding to have the decimal section

2019-10-24 14:10 UTC, barahonajm commented on Assigment 1/Example2.java
> +        if (div - (int)div > 0) {
This was another clever way to make it work, great!

2019-10-24 14:10 UTC, barahonajm commented on Assigment 1/Example3.java
> +                isPalindrome &= inputString.toCharArray()[i] == inputString.toCharArray()[length - i];
The only problem with this is that you are still checking all letters even if the first one is already different, could you please fix that, you can possible add `if (i != length - i  &&  isPalindrome)`

`

2019-10-25 15:52 UTC, uabarahona approved these changes

2019-10-25 16:09 UTC, Regis25 commented
Thank you very much

2019-10-25 16:09 UTC, merged